common/models/MhConsItems.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "mh_cons_items".
 *
 * @property int $cons_items_id รหัสสินค้า
 * @property string|null $cons_item_name ชื่อสินค้า
 * @property int|null $cons_item_level ลำดับสินค้า
 * @property int|null $cons_product_id ประเภทสินค้า
 * @property float|null $cons_price ราคาสินค้า
 * @property int|null $cons_id รหัสกิจการ
 * @property int|null $user_id ผู้ใช้
 * @property int|null $cons_pt_id
 * @property int|null $cons_sub_pt_id
 * @property int|null $cons_sub_type_id
 * @property int|null $cons_province_id
 * @property int|null $cons_amphoe_id
 * @property int|null $updated_id
 * @property string $created_time เวลาสร้าง
 * @property string $updated_time เวลาแก้ไข
 *
 * @property MhConstruction $cons
 * @property MhProvince $consProvince
 * @property MhAmphoe $consAmphoe
 * @property MhUser $user
 * @property MhConsProduct $consProduct
 * @property MhConstructionProductType $consPt
 * @property MhConsSubPt $consSubPt
 * @property MhConsSubType $consSubType
 */
class MhConsItems extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mh_cons_items';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cons_item_level', 'cons_product_id', 'cons_id', 'user_id', 'cons_pt_id', 'cons_sub_pt_id', 'cons_sub_type_id', 'cons_province_id', 'cons_amphoe_id', 'updated_id'], 'integer'],
            [['cons_price'], 'number'],
            [['created_time', 'cons_id'], 'required'],
            [['created_time', 'updated_time'], 'safe'],
            [['cons_item_name'], 'string', 'max' => 255],
            [['cons_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConstruction::className(), 'targetAttribute' => ['cons_id' => 'cons_id']],
            [['cons_province_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhProvince::className(), 'targetAttribute' => ['cons_province_id' => 'province_id']],
            [['cons_amphoe_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhAmphoe::className(), 'targetAttribute' => ['cons_amphoe_id' => 'amphoe_id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhUser::className(), 'targetAttribute' => ['user_id' => 'user_id']],
            [['cons_product_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConsProduct::className(), 'targetAttribute' => ['cons_product_id' => 'cons_product_id']],
            [['cons_pt_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConstructionProductType::className(), 'targetAttribute' => ['cons_pt_id' => 'cons_pt_id']],
            [['cons_sub_pt_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConsSubPt::className(), 'targetAttribute' => ['cons_sub_pt_id' => 'cons_sub_pt_id']],
            [['cons_sub_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConsSubType::className(), 'targetAttribute' => ['cons_sub_type_id' => 'cons_sub_type_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cons_items_id' => 'รหัสสินค้า',
            'cons_item_name' => 'ชื่อสินค้า',
            'cons_item_level' => 'ลำดับสินค้า',
            'cons_product_id' => 'ประเภทสินค้า',
            'cons_price' => 'ราคาสินค้า',
            'cons_id' => 'ชื่อกิจการ',
            'user_id' => 'ชื่อเจ้าของกิจการ',
            'cons_pt_id' => 'ประเภทสินค้า',
            'cons_sub_pt_id' => 'ประเภทสินค้าย่อย',
            'cons_sub_type_id' => 'ประเภทสินค้าย่อยๆ',
            'cons_province_id' => 'พื้นที่จังหวัด',
            'cons_amphoe_id' => 'พื้นที่อำเภอ',
            'updated_id' => 'ชื่อผู้แก้ไข',
            'created_time' => 'วันเวลาสร้าง',
            'updated_time' => 'วันเวลาแก้ไข',
        ];
    }

    public function getCons()
    {
        return $this->hasOne(MhConstruction::className(), ['cons_id' => 'cons_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsProvince()
    {
        return $this->hasOne(MhProvince::className(), ['province_id' => 'cons_province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsAmphoe()
    {
        return $this->hasOne(MhAmphoe::className(), ['amphoe_id' => 'cons_amphoe_id']);
    }

       /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsRouteProvince()
    {
        return $this->hasOne(MhConsRoute::className(), ['cons_route_province_id' => 'cons_province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsRouteAmphoe()
    {
        return $this->hasOne(MhConsRoute::className(), ['cons_route_amphoe_id' => 'cons_amphoe_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(MhUser::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsProduct()
    {
        return $this->hasOne(MhConsProduct::className(), ['cons_product_id' => 'cons_product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsPt()
    {
        return $this->hasOne(MhConstructionProductType::className(), ['cons_pt_id' => 'cons_pt_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsSubPt()
    {
        return $this->hasOne(MhConsSubPt::className(), ['cons_sub_pt_id' => 'cons_sub_pt_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsSubType()
    {
        return $this->hasOne(MhConsSubType::className(), ['cons_sub_type_id' => 'cons_sub_type_id']);
    } 

    public function getDefaultLevel() {

        $result = '';
        if (($this->cons_item_level != null) && ($this->cons_item_level != '')) {
            $resultcoll = MhConsItems::find()
                ->where(['cons_item_level' => $this->cons_item_level])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->cons_item_level;
            } else {
                $result = '100';
            }
        } else {
            $result = '100';
        }
        return $result;
        
   }

    
    public function getProductTypes()
    {
        if (($model = MhConsProduct::find()) !== null) {
            return ArrayHelper::map(
                MhConsProduct::find()->all(),
                'cons_product_id',
                function ($model) {
                    if ( $model['cons_pt_id'] == $model['cons_sub_pt_id']) return $model['cons_pt_id'];
                    else return $model->consPt->cons_pt_name . ' - ' . $model->consSubPt->cons_sub_pt_name;
                }
            );
        }

        return array(-1, 'No car data');
    }

    public function pickup()
    {
        $result = '';
        if (($this->cons_province_id != null) && ($this->cons_province_id != '')) {
            $resultcoll = MhProvince::find()
                ->where(['province_id' => $this->cons_province_id])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->province_name_th;
            } else {
                $result = 'ไม่ระบุ';
            }
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

    public function deliver()
    {
        $result = '';
        if (($this->cons_amphoe_id != null) && ($this->cons_amphoe_id != '')) {
            $resultcoll = MhAmphoe::find()
                ->where(['amphoe_id' => $this->cons_amphoe_id])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->amphoe_name_th;
            } else {
                $result = 'ไม่ระบุ';
            }
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

    


}

backend/controllers/MhConsItemsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\MhConsItems;
use backend\models\MhConsItemsSearch;
use backend\models\MhConsProductSearch;
use backend\models\MhConstructionSearch;
use common\models\MhAmphoe;
use common\models\MhConsProduct;
use common\models\MhConsSubPt;
use common\models\MhConsSubType;
use common\models\MhConstruction;
use common\models\MhConstructionProductType;
use yii\data\Pagination;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * MhConsItemsController implements the CRUD actions for MhConsItems model.
 */
class MhConsItemsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MhConsItems models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MhConsItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);




        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    public function actionAddproductlists()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;
        $model = new MhConsProductSearch();
        $searchModel = new MhConsProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $subpt = ArrayHelper::map($this->getSubpt($model->cons_pt_id), 'id', 'name');

        $consloops = MhConsProduct::find();
        $pagination = new Pagination([
            'totalCount' => $consloops->count(),
            'defaultPageSize' => 27
        ]);

        /*$countQuery =  clone $consloops;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);*/
        $modelsLimits = $consloops->orderBy('')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        /*var_dump($countQuery);
        die();*/

        return $this->render('addproductlists', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'consloops' => $consloops,
            'modelsLimits' => $modelsLimits,
            'pagination' => $pagination,
            'subpt' => $subpt,
        ]);
    }

    public function actionUpdateproduct($id)
    {
        $model = $this->findModel($id);

        /*$subpt = ArrayHelper::map($this->getSubpt($model->cons_pt_id), 'id', 'name');
        $subtype = ArrayHelper::map($this->getSubtype($model->cons_sub_pt_id), 'id', 'name');*/
        if ($model->load(Yii::$app->request->post())) {

            if ($model->save()) {

                return $this->redirect(['view', 'id' => $model->cons_items_id]);
            }
        }

        return $this->render('updateproduct', [
            'model' => $model,
            //'modelpro' => $modelpro,
            /*'subpt' => $subpt,
            'subtype' => $subtype,*/

        ]);
    }

    public function actionMyitemscons($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;


        $model = MhConstruction::findOne($id);
        $modelcons = new MhConstructionSearch();
        /*var_dump($id);
                die();*/
        $searchModel = new MhConsItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $amphoe = ArrayHelper::map($this->getAmphoe($modelcons->cons_amphoe_id), 'id', 'name');
        $subpt = ArrayHelper::map($this->getSubpt($modelcons->cons_pt_id), 'id', 'name');
        $dataProvider
            ->query
            ->andFilterWhere(['in', 'cons_id', $id]);

        $consloops = MhConsItems::find()
            ->where(['in', 'cons_id', $id]);


        $pagination = new Pagination([
            'totalCount' => $consloops->count(),
            'defaultPageSize' => 27
        ]);

        /*$countQuery =  clone $consloops;
            $pages = new Pagination(['totalCount' => $countQuery->count()]);*/
        $modelsLimits = $consloops->orderBy('cons_item_level')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        /*var_dump($countQuery);
            die();*/

        return $this->render('my_cons_items', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'consloops' => $consloops,
            'modelsLimits' => $modelsLimits,
            'pagination' => $pagination,
            'id' => $model->cons_id,
            'amphoe' => $amphoe,
            'subpt' => $subpt,
            'modelcons' => $modelcons,
        ]);
    }

    /**
     * Displays a single MhConsItems model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MhConsItems model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new MhConsItems();
        $modelpro = MhConsProduct::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cons_items_id]);
        }

        return $this->render('create', [
            'model' => $model,
            'modelpro' => $modelpro,
        ]);
    }

    /**
     * Updates an existing MhConsItems model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $subpt = ArrayHelper::map($this->getSubpt($model->cons_pt_id), 'id', 'name');
        $subtype = ArrayHelper::map($this->getSubtype($model->cons_sub_pt_id), 'id', 'name');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cons_items_id]);
        }

        return $this->render('update', [
            'model' => $model,
            'subpt' => $subpt,
            'subtype' => $subtype,
        ]);
    }

    /**
     * Deletes an existing MhConsItems model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MhConsItems model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MhConsItems the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MhConsItems::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function getProductTypes()
    {
        if (($model = MhConsProduct::find()) !== null) {
            return ArrayHelper::map(
                MhConsProduct::find()->all(),
                'cons_product_id',
                function ($model) {
                    if ($model['cons_pt_id'] == $model['cons_sub_pt_id']) return $model['cons_pt_id'];
                    else return $model->consPt->cons_pt_name . ' - ' . $model->consSubPt->cons_sub_pt_name;
                }
            );
        }

        return array(-1, 'No car data');
    }

    public function actionGetAmphoe()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $province_id = $parents[0];
                $out = $this->getAmphoe($province_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getAmphoe($id)
    {
        $datas = MhAmphoe::find()->where(['province_id' => $id])->orderBy('amphoe_name_th')->all();
        return $this->MapData($datas, 'amphoe_id', 'amphoe_name_th');
    }

    public function actionGetSubpt()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cons_pt_id = $parents[0];
                $out = $this->getSubpt($cons_pt_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionGetSubtype()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $ids = $_POST['depdrop_parents'];
            $cons_pt_id = empty($ids[0]) ? null : $ids[0];
            $cons_sup_pt_id = empty($ids[1]) ? null : $ids[1];
            if ($cons_pt_id != null) {
                $data = $this->getSubtype($cons_sup_pt_id);

frontend/views/mh-cons-items/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use common\models\MhConsProduct;
use common\models\MhConstruction;
use common\models\MhUser;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $model common\models\MhConsItems */
/* @var $form yii\widgets\ActiveForm */
$id = yii::$app->user->identity->id;
$cons_product_id = Yii::$app->getRequest()->getQueryParam('id');
$userid = ArrayHelper::map(MhUser::find()->asArray()->all(), 'user_id', 'user_firstname');
$consproduct = ArrayHelper::map(MhConsProduct::find()->asArray()->all(), 'cons_product_id', 'cons_product_name');
$consid = ArrayHelper::map(MhConstruction::find()->where(['user_id' => $id])->andWhere('cons_id')->asArray()->all(), 'cons_id', 'cons_name');
$cons_id = Yii::$app->getRequest()->getQueryParam('id2');
//var_dump($cons_id); echo '<br>';

?>

<body style="background-color: #ecf0f3;">

<div class="mh-cons-items-form">

    <?php $form = ActiveForm::begin(); ?>

    <div class="card2" style="padding-top:30px">
        <div class="rounded mx-auto d-block text-center">
                <div class="gImg ">
                    <p class="card-img-top"><?= $modelpro->getPhotosViewer() ?></p>
                </div>
        </div>

        <div id="myModal" class="modal">
                <span class="close">×</span>
                    <img class="modal-content" id="img01">
                <div id="caption"></div>
            </div>

        <div class="card-body">

            <p class="card-text">ชื่อสินค้า : <?= $modelpro->cons_product_name ?></p>
            <p class="card-text">รายละเอียด : <?= nl2br($modelpro->cons_product_description) ?></p>    
            <p class="card-text">หมวด : <?= $modelpro->consPt->cons_pt_name ?></p>
            <p class="card-text">หมู่ : <?= $modelpro->consSubPt->cons_sub_pt_name ?></p>
            <p class="card-text">หมู่ย่อย : <?= $modelpro->subtype() ?></p>
            

        </div>
    </div>

            <br>



    <div class="card2">

            <h2 style="padding-left:20px; padding-top:20px;">เพิ่มสินค้าลงในร้านค้าของฉัน</h2>

        <div class="card-body">
            
            <?= 
                $form
                    ->field($model, 'cons_item_level')
                    ->hiddenInput(['maxlength' => true, 'value' => $model->getDefaultLevel()])
                    //->input('', ['placeholder' => ""])
                    ->label(false) 
            ?>
            


            <?= 
                $form
                    ->field($model, 'cons_product_id')
                    ->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $cons_product_id])
                    ->label(false)
            ?>



            <div class="">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <?=''
                        /*$form
                            ->field($model, 'cons_product_id')
                            ->widget(Select2::classname(), [
                                'data' => $this->context->getProductTypes(),
                                'language' => 'th',
                                'options' => ['multiple' => true, 'placeholder' => 'เลือกประเภทสินค้า'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                        ]);*/                 
                    ?>
                </div>
            </div>   



            <?= $form->field($model, 'cons_price')->textInput(['maxlength' => true]) ?>


            <?= $form->field($model, 'cons_id')
                            ->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $cons_id])
                            ->label(false)
            ?>


            <?='' /*$form->field($model, 'cons_id')
                            ->dropdownList($consid, [
                                'id' => 'ddl-roguser',        
                                'prompt' => 'เลือกร้านของฉัน'                
                            ])
                            ->label('ร้านค้าของฉัน')*/
            ?>

            <?= $form->field($model, 'user_id')
                            ->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $id])
                            ->label(false)
            ?>
            

            <?= $form->field($model, 'cons_pt_id')
                            ->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $modelpro->consPt->cons_pt_id])
                            ->label(false)
            ?>  

            <?= $form->field($model, 'cons_sub_pt_id')
                            ->hiddenInput(['maxlength' => true, 'readonly' => true, 'value' => $modelpro->consSubPt->cons_sub_pt_id])
                            ->label(false)
            ?>  

            <?='' /*$form->field($model, 'cons_sub_type_id')
                            ->textInput(['maxlength' => true, 'readonly' => true, 'value' => $modelpro->subtype()])
                            ->label(false)*/
            ?>  

            

            


            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <?=''
                        /*$form
                            ->field($model, 'cons_product_id')
                            ->widget(Select2::classname(), [
                                'data' => $this->context->getProductTypes(),
                                'language' => 'th',
                                'options' => ['multiple' => true, 'placeholder' => 'เลือกประเภทสินค้า'],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                        ]);*/                 
                    ?>
                </div>
            </div>



            <?='' /*$form->field($model, 'cons_id')
                            ->textInput(['maxlength' => true, 'readonly' => true, 'value' => $consid])
                            ->label(false)*/
            ?>




                            
            <?= $form->field($model, 'created_time')->textInput([
                'readonly' => true,
                'value' => (($model->created_time != null) && ($model->created_time != '0000-00-00 00:00:00')) ? $model->created_time : date('Y-m-d H:i:s')
            ]) ?>

            <?= $form->field($model, 'updated_time')->textInput([
                'readonly' => true,
                'value' => date('Y-m-d H:i:s')
            ]) ?>

            <div class="form-group">
                <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
            </div>
        
        </div>
    </div>
    
<br>
    <?php ActiveForm::end(); ?>

</div>
<script>
    // Get the modal
var modal = document.getElementById('myModal');

modal.addEventListener('click',function(){
this.style.display="none";
})

// Get the <span> element that closes the modal
var span = document.getElementsByClassName("close")[0];

// When the user clicks on <span> (x), close the modal
span.onclick = function() {
  modal.style.display = "none";
}

// Get all images and insert the clicked image inside the modal
// Get the content of the image description and insert it inside the modal image caption
var images = document.getElementsByTagName('img');
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
var i;
for (i = 0; i < images.length; i++) {
  images[i].onclick = function() {
    modal.style.display = "block";
    modalImg.src = this.src;
    modalImg.alt = this.alt;
    captionText.innerHTML = this.nextElementSibling.innerHTML;
  }
}
</script>

</body>

frontend/views/mh-cons-items/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhConsItems */

$this->title = 'รายละเอียดสินค้า : ' . $modelpro->cons_product_name;
$consid = Yii::$app->getRequest()->getQueryParam('id');
$this->params['breadcrumbs'][] = ['label' => 'สินค้าที่สามารถเพิ่มได้' , 'url' => ['mh-cons-items/addproductlists']];
/*if (Yii::$app->user->isGuest) {
    
    $this->params['breadcrumbs'][] = ['label' => 'สินค้าภายในร้าน', 'url' => ['mh-cons-items/itemsstore', 'id' => $model->cons_id]];

} else {    

    $this->params['breadcrumbs'][] = ['label' => 'สินค้าภายในร้านของฉัน', 'url' => ['mh-cons-items/myitems', 'id' => $model->cons_id, ]];

}*/
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mh-cons-items-create">

    <div class="card2">
        <h1 style="padding-left:20px; padding-top:20px;"><?= Html::encode($this->title) ?></h1>
    </div>

    <?= $this->render('_form', [
        'model' => $model,
        'modelpro' => $modelpro,
        'modelcons' => $modelcons,
    ]) ?>

</div>

frontend/views/mh-cons-items/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\MhConsItemsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Mh Cons Items';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mh-cons-items-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Mh Cons Items', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'cons_items_id',
            'cons_product_id',
            'cons_price',
            'cons_id',
            'user_id',
            //'updated_id',
            //'created_time',
            //'updated_time',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

frontend/views/mh-cons-items/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhConsItems */

$this->title = 'แก้ไขข้อมูลสินค้า: ' . $model->cons_product_id;
$consid = Yii::$app->getRequest()->getQueryParam('id');
$this->params['breadcrumbs'][] = ['label' => 'ร้านค้า' , 'url' => ['mh-construction/view','id' => $consid]];
if (Yii::$app->user->isGuest) {
    
    $this->params['breadcrumbs'][] = ['label' => 'สินค้าภายในร้าน', 'url' => ['mh-cons-items/itemsstore', 'id' => $model->cons_id]];
    
} else {    

    $this->params['breadcrumbs'][] = ['label' => 'สินค้าภายในร้านของฉัน', 'url' => ['mh-cons-items/myitems', 'id' => $consid, ]];

}
$this->params['breadcrumbs'][] = ['label' => $model->cons_product_id, 'url' => ['view', 'id' => $model->cons_items_id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="mh-cons-items-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'modelpro' => $modelpro,
        'modelcons' => $modelcons,
    ]) ?>

</div>