common/models/MhConsItems.php
<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "mh_cons_items".
 *
 * @property int $cons_items_id รหัสสินค้า
 * @property string|null $cons_item_name ชื่อสินค้า
 * @property int|null $cons_item_level ลำดับสินค้า
 * @property int|null $cons_product_id ประเภทสินค้า
 * @property float|null $cons_price ราคาสินค้า
 * @property int|null $cons_id รหัสกิจการ
 * @property int|null $user_id ผู้ใช้
 * @property int|null $cons_pt_id
 * @property int|null $cons_sub_pt_id
 * @property int|null $cons_sub_type_id
 * @property int|null $cons_province_id
 * @property int|null $cons_amphoe_id
 * @property int|null $updated_id
 * @property string $created_time เวลาสร้าง
 * @property string $updated_time เวลาแก้ไข
 *
 * @property MhConstruction $cons
 * @property MhProvince $consProvince
 * @property MhAmphoe $consAmphoe
 * @property MhUser $user
 * @property MhConsProduct $consProduct
 * @property MhConstructionProductType $consPt
 * @property MhConsSubPt $consSubPt
 * @property MhConsSubType $consSubType
 */
class MhConsItems extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mh_cons_items';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['cons_item_level', 'cons_product_id', 'cons_id', 'user_id', 'cons_pt_id', 'cons_sub_pt_id', 'cons_sub_type_id', 'cons_province_id', 'cons_amphoe_id', 'updated_id'], 'integer'],
            [['cons_price'], 'number'],
            [['created_time', 'cons_id'], 'required'],
            [['created_time', 'updated_time'], 'safe'],
            [['cons_item_name'], 'string', 'max' => 255],
            [['cons_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConstruction::className(), 'targetAttribute' => ['cons_id' => 'cons_id']],
            [['cons_province_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhProvince::className(), 'targetAttribute' => ['cons_province_id' => 'province_id']],
            [['cons_amphoe_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhAmphoe::className(), 'targetAttribute' => ['cons_amphoe_id' => 'amphoe_id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhUser::className(), 'targetAttribute' => ['user_id' => 'user_id']],
            [['cons_product_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConsProduct::className(), 'targetAttribute' => ['cons_product_id' => 'cons_product_id']],
            [['cons_pt_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConstructionProductType::className(), 'targetAttribute' => ['cons_pt_id' => 'cons_pt_id']],
            [['cons_sub_pt_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConsSubPt::className(), 'targetAttribute' => ['cons_sub_pt_id' => 'cons_sub_pt_id']],
            [['cons_sub_type_id'], 'exist', 'skipOnError' => true, 'targetClass' => MhConsSubType::className(), 'targetAttribute' => ['cons_sub_type_id' => 'cons_sub_type_id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'cons_items_id' => 'รหัสสินค้า',
            'cons_item_name' => 'ชื่อสินค้า',
            'cons_item_level' => 'ลำดับสินค้า',
            'cons_product_id' => 'ประเภทสินค้า',
            'cons_price' => 'ราคาสินค้า',
            'cons_id' => 'ชื่อกิจการ',
            'user_id' => 'ชื่อเจ้าของกิจการ',
            'cons_pt_id' => 'ประเภทสินค้า',
            'cons_sub_pt_id' => 'ประเภทสินค้าย่อย',
            'cons_sub_type_id' => 'ประเภทสินค้าย่อยๆ',
            'cons_province_id' => 'พื้นที่จังหวัด',
            'cons_amphoe_id' => 'พื้นที่อำเภอ',
            'updated_id' => 'ชื่อผู้แก้ไข',
            'created_time' => 'วันเวลาสร้าง',
            'updated_time' => 'วันเวลาแก้ไข',
        ];
    }

    public function getCons()
    {
        return $this->hasOne(MhConstruction::className(), ['cons_id' => 'cons_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsProvince()
    {
        return $this->hasOne(MhProvince::className(), ['province_id' => 'cons_province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsAmphoe()
    {
        return $this->hasOne(MhAmphoe::className(), ['amphoe_id' => 'cons_amphoe_id']);
    }

       /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsRouteProvince()
    {
        return $this->hasOne(MhConsRoute::className(), ['cons_route_province_id' => 'cons_province_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsRouteAmphoe()
    {
        return $this->hasOne(MhConsRoute::className(), ['cons_route_amphoe_id' => 'cons_amphoe_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(MhUser::className(), ['user_id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsProduct()
    {
        return $this->hasOne(MhConsProduct::className(), ['cons_product_id' => 'cons_product_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsPt()
    {
        return $this->hasOne(MhConstructionProductType::className(), ['cons_pt_id' => 'cons_pt_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsSubPt()
    {
        return $this->hasOne(MhConsSubPt::className(), ['cons_sub_pt_id' => 'cons_sub_pt_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConsSubType()
    {
        return $this->hasOne(MhConsSubType::className(), ['cons_sub_type_id' => 'cons_sub_type_id']);
    } 

    public function getDefaultLevel() {

        $result = '';
        if (($this->cons_item_level != null) && ($this->cons_item_level != '')) {
            $resultcoll = MhConsItems::find()
                ->where(['cons_item_level' => $this->cons_item_level])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->cons_item_level;
            } else {
                $result = '100';
            }
        } else {
            $result = '100';
        }
        return $result;
        
   }

    
    public function getProductTypes()
    {
        if (($model = MhConsProduct::find()) !== null) {
            return ArrayHelper::map(
                MhConsProduct::find()->all(),
                'cons_product_id',
                function ($model) {
                    if ( $model['cons_pt_id'] == $model['cons_sub_pt_id']) return $model['cons_pt_id'];
                    else return $model->consPt->cons_pt_name . ' - ' . $model->consSubPt->cons_sub_pt_name;
                }
            );
        }

        return array(-1, 'No car data');
    }

    public function pickup()
    {
        $result = '';
        if (($this->cons_province_id != null) && ($this->cons_province_id != '')) {
            $resultcoll = MhProvince::find()
                ->where(['province_id' => $this->cons_province_id])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->province_name_th;
            } else {
                $result = 'ไม่ระบุ';
            }
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

    public function deliver()
    {
        $result = '';
        if (($this->cons_amphoe_id != null) && ($this->cons_amphoe_id != '')) {
            $resultcoll = MhAmphoe::find()
                ->where(['amphoe_id' => $this->cons_amphoe_id])
                ->one();

            if ($resultcoll) {
                $result = $resultcoll->amphoe_name_th;
            } else {
                $result = 'ไม่ระบุ';
            }
        } else {
            $result = 'ไม่ระบุ';
        }
        return $result;
    }

    


}

backend/controllers/MhConsItemsController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\MhConsItems;
use backend\models\MhConsItemsSearch;
use backend\models\MhConsProductSearch;
use backend\models\MhConstructionSearch;
use common\models\MhAmphoe;
use common\models\MhConsProduct;
use common\models\MhConsSubPt;
use common\models\MhConsSubType;
use common\models\MhConstruction;
use common\models\MhConstructionProductType;
use yii\data\Pagination;
use yii\db\Query;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\helpers\Json;

/**
 * MhConsItemsController implements the CRUD actions for MhConsItems model.
 */
class MhConsItemsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MhConsItems models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MhConsItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);




        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    public function actionAddproductlists()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;
        $model = new MhConsProductSearch();
        $searchModel = new MhConsProductSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $subpt = ArrayHelper::map($this->getSubpt($model->cons_pt_id), 'id', 'name');

        $consloops = MhConsProduct::find();
        $pagination = new Pagination([
            'totalCount' => $consloops->count(),
            'defaultPageSize' => 27
        ]);

        /*$countQuery =  clone $consloops;
        $pages = new Pagination(['totalCount' => $countQuery->count()]);*/
        $modelsLimits = $consloops->orderBy('')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        /*var_dump($countQuery);
        die();*/

        return $this->render('addproductlists', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'consloops' => $consloops,
            'modelsLimits' => $modelsLimits,
            'pagination' => $pagination,
            'subpt' => $subpt,
        ]);
    }

    public function actionUpdateproduct($id)
    {
        $model = $this->findModel($id);

        /*$subpt = ArrayHelper::map($this->getSubpt($model->cons_pt_id), 'id', 'name');
        $subtype = ArrayHelper::map($this->getSubtype($model->cons_sub_pt_id), 'id', 'name');*/
        if ($model->load(Yii::$app->request->post())) {

            if ($model->save()) {

                return $this->redirect(['view', 'id' => $model->cons_items_id]);
            }
        }

        return $this->render('updateproduct', [
            'model' => $model,
            //'modelpro' => $modelpro,
            /*'subpt' => $subpt,
            'subtype' => $subtype,*/

        ]);
    }

    public function actionMyitemscons($id)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;


        $model = MhConstruction::findOne($id);
        $modelcons = new MhConstructionSearch();
        /*var_dump($id);
                die();*/
        $searchModel = new MhConsItemsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $amphoe = ArrayHelper::map($this->getAmphoe($modelcons->cons_amphoe_id), 'id', 'name');
        $subpt = ArrayHelper::map($this->getSubpt($modelcons->cons_pt_id), 'id', 'name');
        $dataProvider
            ->query
            ->andFilterWhere(['in', 'cons_id', $id]);

        $consloops = MhConsItems::find()
            ->where(['in', 'cons_id', $id]);


        $pagination = new Pagination([
            'totalCount' => $consloops->count(),
            'defaultPageSize' => 27
        ]);

        /*$countQuery =  clone $consloops;
            $pages = new Pagination(['totalCount' => $countQuery->count()]);*/
        $modelsLimits = $consloops->orderBy('cons_item_level')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();
        /*var_dump($countQuery);
            die();*/

        return $this->render('my_cons_items', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'consloops' => $consloops,
            'modelsLimits' => $modelsLimits,
            'pagination' => $pagination,
            'id' => $model->cons_id,
            'amphoe' => $amphoe,
            'subpt' => $subpt,
            'modelcons' => $modelcons,
        ]);
    }

    /**
     * Displays a single MhConsItems model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MhConsItems model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new MhConsItems();
        $modelpro = MhConsProduct::findOne($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cons_items_id]);
        }

        return $this->render('create', [
            'model' => $model,
            'modelpro' => $modelpro,
        ]);
    }

    /**
     * Updates an existing MhConsItems model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $subpt = ArrayHelper::map($this->getSubpt($model->cons_pt_id), 'id', 'name');
        $subtype = ArrayHelper::map($this->getSubtype($model->cons_sub_pt_id), 'id', 'name');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cons_items_id]);
        }

        return $this->render('update', [
            'model' => $model,
            'subpt' => $subpt,
            'subtype' => $subtype,
        ]);
    }

    /**
     * Deletes an existing MhConsItems model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MhConsItems model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MhConsItems the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MhConsItems::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function getProductTypes()
    {
        if (($model = MhConsProduct::find()) !== null) {
            return ArrayHelper::map(
                MhConsProduct::find()->all(),
                'cons_product_id',
                function ($model) {
                    if ($model['cons_pt_id'] == $model['cons_sub_pt_id']) return $model['cons_pt_id'];
                    else return $model->consPt->cons_pt_name . ' - ' . $model->consSubPt->cons_sub_pt_name;
                }
            );
        }

        return array(-1, 'No car data');
    }

    public function actionGetAmphoe()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $province_id = $parents[0];
                $out = $this->getAmphoe($province_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    protected function getAmphoe($id)
    {
        $datas = MhAmphoe::find()->where(['province_id' => $id])->orderBy('amphoe_name_th')->all();
        return $this->MapData($datas, 'amphoe_id', 'amphoe_name_th');
    }

    public function actionGetSubpt()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                $cons_pt_id = $parents[0];
                $out = $this->getSubpt($cons_pt_id);
                echo Json::encode(['output' => $out, 'selected' => '']);
                return;
            }
        }
        echo Json::encode(['output' => '', 'selected' => '']);
    }

    public function actionGetSubtype()
    {
        $out = [];
        if (isset($_POST['depdrop_parents'])) {
            $ids = $_POST['depdrop_parents'];
            $cons_pt_id = empty($ids[0]) ? null : $ids[0];
            $cons_sup_pt_id = empty($ids[1]) ? null : $ids[1];
            if ($cons_pt_id != null) {
                $data = $this->getSubtype($cons_sup_pt_id);

backend/views/mh-cons-items/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\MhConsItemsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mh-cons-items-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'cons_items_id') ?>

    <?= $form->field($model, 'cons_product_id') ?>

    <?= $form->field($model, 'cons_price') ?>

    <?= $form->field($model, 'cons_id') ?>

    <?= $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'updated_id') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'updated_time') ?>

    <div class="form-group">
        <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('รีเซ็ท', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/mh-cons-items/_searchproduct.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\MhProvince;
use common\models\MhAmphoe;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use kartik\widgets\DepDrop;

/* @var $this yii\web\View */
/* @var $model frontend\models\MhConsItemsSearch */
/* @var $form yii\widgets\ActiveForm */
$province = ArrayHelper::map(MhProvince::find()->asArray()->all(), 'province_id', 'province_name_th');

?>

<div class="mh-cons-items-search">

    <?php $form = ActiveForm::begin([
        'action' => ['addproductlists'],
        'method' => 'get',
    ]); ?>

<div class="panel panel-default" >

    <h1 style="padding-left:20px; padding-top:20px;">สินค้าวัสดุก่อสร้าง</h1>

<div class="row panel-body">


    <div class="col-sm-3">
        <?= 
            $form
                ->field($model, 'cons_pt_id')
                ->dropDownList(
                    $this->context->getConsTypes(),
                    [ 'separator' => '<br>',
                    'id' => 'ddl-cons_pt_id',
                    'prompt' => 'เลือกหมวดหมู่วัสดุก่อสร้าง' 
                    
                ])
                
                ->label(false)
               
        ?>
    </div>  

    <div class="col-md-3">
        <?=
            $form
                ->field($model, 'cons_sub_pt_id')
                ->widget(DepDrop::classname(), [
                    'options' => ['id' => 'ddl-cons_sub_pt_id'],
                    'data' => $subpt,
                    'pluginOptions' => [
                        'depends' => ['ddl-cons_pt_id'],
                        'placeholder' => 'เลือกประเภทย่อยของสินค้าวัสดุ',
                        'url' => Url::to(['/mh-cons-items/get-subpt'])
                    ]
                ])
                ->label(false);
        ?>
    </div>






                    
    <div class="col-8 col-sm-3">
            <div class="form-group">
                <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary btn-block', 'id' => 'btnSubmit']) ?>
            </div>
    </div>

    <div class="col-4 col-sm-3">    
        <div class="form-group">       
            <?= Html::a(
                'รีเซ็ต',
                ['mh-cons-items/addproductlists'],
                ['class' => 'btn btn-danger btn-block', 'style' => '']
            ) ?>
        </div>
    </div>

       



<!--<div class="col-xs-12 col-sm-12 col-md-12">
    <p> </p>
</div>-->

<!--<div class="col-xs-12 col-sm-12 col-md-12"> 
       
       <?= Html::a(
           '<i class="fab fa-facebook-square"></i> Rogistic.com',
           'https://www.facebook.com/Rogisticcom-359767341103161',
           ['class' => 'btn btn-primary  btn-block btn-lg']

           )
       ?>

</div>-->


<?php ActiveForm::end(); ?>


    </div>


    </div>

</div>

backend/views/mh-cons-items/addproductlists.php
<?php

use common\models\MhConstruction;
use yii\bootstrap4\Html;
use yii\grid\GridView;
use yii\bootstrap4\LinkPager;
use yii\helpers\ArrayHelper;


/* @var $this yii\web\View */
/* @var $searchModel app\models\RogUserCarSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$consid = Yii::$app->getRequest()->getQueryParam('id');

$this->title = 'สินค้าที่สามารถเพิ่มได้';
$this->params['breadcrumbs'][] = ['label' => 'ร้านค้า', 'url' => ['mh-construction/view','id' => $consid]];
$this->params['breadcrumbs'][] = $this->title;

Yii::$app->params['og_title']['content'] = $this->title;


Yii::$app->params['og_url']['content'] = 'https://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'];
Yii::$app->params['og_keyword']['content'] = 'ร้านวัสดุก่อสร้าง ,hub.maxhome ,สินค้าร้านวัสดุก่อสร้าง';
Yii::$app->params['og_revisit_after']['content'] = '1 Days';


?>

<body>
  


<div class="mh-job-index">



<?php echo $this->render('_searchproduct', ['model' => $searchModel, 'subpt' => $subpt,]); ?>
  

  <div class="col-xs-12 col-sm-12 col-md-12">
            <p> </p>
        </div>

        
        <div class="container">
    <div class=" row ">

      <?php foreach ($dataProvider->models as $model) { ?>
        
        <?= Html::a('<div class="">
                          <div class="panel panel-default" >
                            <div class=""> 
                            ' . Html::img($model->getFirstPhotoURL(), ['class' => 'img-responsive rounded mx-auto d-block commany-display-mobile commany-image576px commany-image768px']) . '                      
                            </div>

                            <div class="panel-body">
                              <h6 class="card-title">' . $model->cons_product_name . ' </h6>
                              
                              
                              
                              
                            </div>  

                          </div>
                        </div>', ['create', 'id' => $model->cons_product_id], ['class' => '', 'style' => 'text-decoration: none; color:black;'])
        ?>

      <?php } ?>



    </div>
    <br>
  </div>


      <?php if (!empty($dataProvider->models)) : ?>            
        <?php
                    echo \yii\bootstrap4\LinkPager::widget([
                    'pagination' => $pagination,
                ]);
        ?>
      <?php else : ?>
            <div class="alert alert-danger" role="alert">
              <?php echo "ไม่พบข้อมูล !!"; ?>
            </div>
      <?php endif; ?>







      </div>
</body>

backend/views/mh-cons-items/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhConsItems */

$this->title = 'เพิ่มข้อมูลสินค้าวัสดุก่อสร้าง';
$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลสินค้าวัสดุก่อสร้าง', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mh-cons-items-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'subpt' => [],
        'subtype' => [],
        'modelpro' => $modelpro,
    ]) ?>

</div>

backend/views/mh-cons-items/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhConsItems */

$this->title = 'แก้ไขข้อมูลสินค้าวัสดุก่อสร้าง: ' . $model->cons_items_id;
$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลสินค้าวัสดุก่อสร้าง', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->cons_items_id, 'url' => ['view', 'id' => $model->cons_items_id]];
$this->params['breadcrumbs'][] = 'แก้ไข';
?>
<div class="mh-cons-items-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'subpt' => $subpt,
        'subtype' => $subtype,
    ]) ?>

</div>

backend/views/mh-cons-items/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\MhConsItems */

$this->title = $model->consPt->cons_pt_name .' - '. $model->consSubPt->cons_sub_pt_name;
$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลสินค้าวัสดุก่อสร้าง', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$cons_id = Yii::$app->getRequest()->getQueryParam('id');
\yii\web\YiiAsset::register($this);
?>
<div class="mh-cons-items-view">

    <h1>ชื่อสินค้า : <?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('เพิ่มข้อมูล', ['addproductlists'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('แก้ไข', ['updateproduct', 'id' => $model->cons_items_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('ลบ', ['delete', 'id' => $model->cons_items_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'คุณต้องการลบรายการนี้หรือไม่?',
                'method' => 'post',
            ],
        ]) ?>
        <?= Html::a('+ เพิ่มสินค้าร้านวัสดุก่อสร้าง', ['mh-cons-items/addproductlists'], ['class' => 'btn btn-success']) ?>
    </p>

    <div class="panel panel-default" style="padding-top:20px">
        <div class="text-center ">
            <div class="gImg ">
                <p class="card-img-top"><?= $model->consProduct->getPhotosViewerback() ?></p>
            </div>
        </div>
    </div>

    <div class="panel panel-default">
        <div class="panel-body">
            <p class="card-text"><strong>ลำดับการค้นหา</strong> : <?= $model->cons_item_level ?> </p>           
            <p class="card-text"><strong>ประเภทสินค้า</strong> : <?= $model->consProduct->consPt->cons_pt_name ?> - <?= $model->consProduct->consSubPt->cons_sub_pt_name ?></p>
            <p class="card-text"><strong>รายละเอียดสินค้า : <br> <?= nl2br($model->consProduct->cons_product_description) ?></strong></p>
            <p class="card-text"><strong>ราคาสินค้า</strong> : <?= $model->cons_price ?> </p>                     
            <p class="card-text"><strong>ชื่อกิจการ</strong> : <?= $model->cons->cons_name ?> </p>  
                <br>          
            <h4 class="card-text"><strong>ชื่อเจ้าของกิจการ</strong> : <?= $model->user->user_firstname ?></h4>
            <p class="card-text"><strong>เวลาสร้าง</strong> : <?= $model->created_time ?></p>
            <p class="card-text"><strong>เวลาแก้ไข</strong> : <?= $model->updated_time ?></p>
        </div>
    </div>



</div>