common/models/MhUser.php
<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "mh_user".
 *
 * @property int $user_id รหัสผู้ใช้งาน
 * @property string $username ชื่อรหัสผู้ใช้งาน
 * @property string $password รหัสผ่าน
 * @property string $user_firstname ชื่อ
 * @property string $user_lastname นามสกุล
 * @property string $user_tel1 เบอร์ติดต่อ 1
 * @property string $user_tel2 เบอร์ติดต่อ 2
 * @property string $user_line_id Line Id
 * @property string $user_line_ad Line @
 * @property int $user_fb_id facebook_id
 * @property string $user_fb_url Facebook ส่วนตัว URL
 * @property string $user_messenger Messenger
 * @property string $user_email Email
 * @property string $user_website Website
 * @property string $user_other อื่น ๆ
 * @property int $updated_id รหัสเวลาแก้ไข
 * @property string $created_time เวลาสร้าง
 * @property string $updated_time เวลาแก้ไข
 */
class MhUser extends \yii\db\ActiveRecord implements \yii\web\IdentityInterface
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'mh_user';
    }
    public $rememberMe = true;
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_fb_id', 'updated_id'], 'integer'],
            [['created_time', 'updated_time'], 'safe'],
            [['username', 'user_firstname', 'user_lastname', 'user_fb_url', 'user_messenger', 'user_email', 'user_website'], 'string', 'max' => 150],
            [['password', 'user_other'], 'string', 'max' => 255],
            [['user_tel1', 'user_tel2', 'user_line_id', 'user_line_ad'], 'string', 'max' => 50],
            [['username'], 'unique'],
            //['rememberMe', 'boolean']
        ];
    }



    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'user_id' => 'User ID',
            'username' => 'ชื่อรหัสผู้ใช้งาน',
            'password' => 'รหัสผ่าน',
            'user_firstname' => 'ชื่อ',
            'user_lastname' => 'นามสกุล',
            'user_tel1' => 'เบอร์ติดต่อ 1',
            'user_tel2' => 'เบอร์ติดต่อ 2',
            'user_line_id' => 'Line ID',
            'user_line_ad' => 'Line Ad',
            'user_fb_id' => 'facebook_id',
            'user_fb_url' => 'Facebook ส่วนตัว URL',
            'user_messenger' => 'Messenger',
            'user_email' => 'Email',
            'user_website' => 'Website',
            'user_other' => 'อื่น ๆ',
            'updated_id' => 'รหัสเวลาแก้ไข',
            'created_time' => 'เวลาสร้าง',
            'updated_time' => 'เวลาแก้ไข',
        ];
    }



    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        $user = self::findOne(['user_id' => $id]);
        if ($user) {
            //return new static($user->user_id);
            return $user;
        } else return null;
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        $user = self::findOne(['user_fb_id' => $token]);
        if ($user) {
            return new static($user);
        } else return null;
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->user_id;
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->user_fb_id;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->user_fb_id === $authKey;
    }





    /**
     * Finds user by [[username]]
     *
     * @return User|null
     */
    public function getUser()
    {
        return $this;
    }

    public static function findByUsername($username)
    {
        return self::findOne(['username' => $username]);
    }

    public function validatePassword($password)
    {
        return $this->password === $password;
    }
}

backend/controllers/MhUserController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\MhUser;
use backend\models\MhUserSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * MhUserController implements the CRUD actions for MhUser model.
 */
class MhUserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MhUser models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MhUserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single MhUser model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new MhUser model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MhUser();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing MhUser model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MhUser model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MhUser model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MhUser the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MhUser::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/MhUserController.php
<?php

namespace frontend\controllers;

use Yii;
use common\models\MhUser;
use backend\models\MhUserSearch;
use frontend\models\MhStoreSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * MhUserController implements the CRUD actions for MhUser model.
 */
class MhUserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all MhUser models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new MhUserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionProfile()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user = Yii::$app->user->identity;

        return $this->render('profile', [
            'model' => $this->findModel($user->user_id),
        ]);
    }

    public function actionMybusiness()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['site/login']);
        }

        $user_id = Yii::$app->user->identity;
        $user = Yii::$app->user->identity;

        $searchModel = new MhStoreSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider
            ->query
            ->where(['in', 'user_id', $user_id]);


        return $this->render('my_business', [
            'model' => $this->findModel($user->id),
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,



        ]);
    }

    /**
     * Displays a single MhUser model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);
        $owner = false;

        $user_id = Yii::$app->user->id;
        if ($model->user_id == $user_id) {
            $owner = true;
        }

        return $this->render('view', [
            'model' => $this->findModel($id),
            'owner' => $owner,
        ]);
    }

    /**
     * Creates a new MhUser model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new MhUser();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {


            $model->user_password = Yii::$app->security->generatePasswordHash($_POST['user_password']);
            return $this->redirect(['view', 'id' => $model->user_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing MhUser model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['profile', 'id' => $model->user_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing MhUser model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the MhUser model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return MhUser the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = MhUser::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionRegister()
    {

        $model = new MhUser();

        if ($model->load(Yii::$app->request->post())) {

            // $model->password = password_hash($_POST['MhUser']['password'], PASSWORD_ARGON2I);

            if ($model->save()) {
                return $this->redirect(['site/login']);
            }

            return $this->redirect(['site/login']);
        }

        return $this->render('_form_register', [
            'model' => $model,
        ]);
    }

    // public function actionLogin()
    // {
    //     if (!Yii::$app->user->isGuest) {
    //         return $this->goHome();
    //     }

    //     //$model = new LoginForm();
    //     $model = new MhUser();
    //     if ($model->load(Yii::$app->request->post()) && $model->login()) {
    //         return $this->goBack();
    //     } else {
    //         $model->password = '';

    //         return $this->render('login', [
    //             'model' => $model,
    //             //'modeluser' => $modeluser,
    //         ]);
    //     }
    // }
}

frontend/views/mh-user/_form.php
<?php

use yii\bootstrap4\Html;
use yii\bootstrap4\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\MhUser */
/* @var $form yii\widgets\ActiveForm */
$this->title = 'แก้ไขข้อมูลผู้ใช้งาน: ' . $model->user_firstname;
?>

<body style="background-color: #ecf0f3;">

<div class="mh-user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?='' //$form->field($model, 'user_name')->textInput(['maxlength' => true]) ?>

    <div class="card2">

    <h1 style="padding-left:20px; padding-top:20px;"><?= Html::encode($this->title) ?></h1>

        <div class="card-body">
        <?= $form->field($model, 'user_firstname')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'user_lastname')->textInput(['maxlength' => true]) ?>  

        <?= $form->field($model, 'user_tel1')->textInput()->label('เบอร์ติดต่อ 1', ['style' => 'color:red']) ?>

        <?= $form->field($model, 'user_tel2')->textInput() ?>

        <?= $form->field($model, 'user_line_id')->textInput(['maxlength' => true])->label('line id', ['style' => 'color:red']) ?>

        <?='' //$form->field($model, 'user_line_ad')->textInput(['maxlength' => true])->label('line @', ['style' => 'color:red']) ?>

        <?='' //$form->field($model, 'user_fb_id')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'user_fb_url')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'user_messenger')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'user_email')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'user_website')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'user_other')->textInput(['maxlength' => true]) ?>

        <?='' //$form->field($model, 'updated_id')->textInput() ?>

        <?= $form->field($model, 'created_time')->textInput([
            'readonly' => true,
            'value' => (($model->created_time != null) && ($model->created_time != '0000-00-00 00:00:00')) ? $model->created_time : date('Y-m-d H:i:s')
        ]) ?>

        <?= $form->field($model, 'updated_time')->textInput([
            'readonly' => true,
            'value' => date('Y-m-d H:i:s')
        ]) ?>

        <div class="form-group">
            <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
        </div>
        </div>
    </div>

    

    <?php ActiveForm::end(); ?>

</div>

    <div class="">
        <p></p>
    </div>

</body>

frontend/views/mh-user/_form_register.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\mh-user */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mh-user-form">

    <?php $form = ActiveForm::begin(); ?>

    <div>
        <p></p>
    </div>

    <div class="card2">
        <h1 align="center" style="padding-top:10px;">กรอกข้อมูล</h1>
        <div class="card-body">
            <?= $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'user_firstname')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'user_lastname')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'user_email')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'user_tel1')->textInput(['maxlength' => true]) ?>

            <div class="col-xs-12 col-sm-12 col-md-12" style="margin-bottom :10px">
                <?= Html::submitButton('บันทึก', ['class' => 'btn btn-success']) ?>
            </div>

        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/mh-user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\MhUserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="mh-user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'user_id') ?>

    <?= $form->field($model, 'user_name') ?>

    <?= $form->field($model, 'user_tel1') ?>

    <?= $form->field($model, 'user_tel2') ?>

    <?= $form->field($model, 'user_line_id') ?>

    <?php // echo $form->field($model, 'user_line_ad') ?>

    <?php // echo $form->field($model, 'user_fb_url') ?>

    <?php // echo $form->field($model, 'user_messenger') ?>

    <?php // echo $form->field($model, 'user_email') ?>

    <?php // echo $form->field($model, 'user_website') ?>

    <?php // echo $form->field($model, 'user_other') ?>

    <?php // echo $form->field($model, 'updated_id') ?>

    <?php // echo $form->field($model, 'created_time') ?>

    <?php // echo $form->field($model, 'updated_time') ?>

    <div class="form-group">
        <?= Html::submitButton('ค้นหา', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('รีเซ็ท', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

frontend/views/mh-user/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\MhUser */

$this->title = 'เพิ่มข้อมูลผู้ใช้งาน';
$this->params['breadcrumbs'][] = ['label' => 'Mh Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="mh-user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

frontend/views/mh-user/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

$this->title = 'เข้าสู่ระบบ hub.maxhome.co';
Yii::$app->params['og_title']['content'] = $this->title;
Yii::$app->params['og_description']['content'] = "Hub maxhome คือศูนย์ร่วมกิจการรับเหมาก่อสร้าง ช่วยแนะนำ ผู้รับเหมาก่อสร้าง ร้านวัสดุก่อสร้าง ผู้ผลิต ตัวแทนจำหน่าย ที่พร้อมให้บริการทั่วประเทศไทย ให้กับลูกค้าที่กำลังสนใจสินค้าและบริการ
เข้าร่วม Hub maxhome ชุมชนวงการธุรกิจก่อสร้าง เสมือนว่าธุรกิจก่อสร้างของท่านตั้งอยู่ทำเลทองที่มีผู้คนสนใจสินค้าและบริการของท่านตลอดเวลา มี traffic จำนวนมากจากลูกค้าที่มีความต้องการใช้สินค้าและบริการของท่านและสามารถติดต่อไปยังธุรกิจของท่านโดยตรง
• ระบบหน้าร้านค้าวัสดุก่อสร้างออนไลน์สำเร็จรูป ที่ให้เจ้าของธุรกิจในวงการก่อสร้างสามารถเขามาสร้างหน้าร้านของตัวเองได้ง่ายๆ ภายใน 3 นาที
• หน้าร้านธุรกิจก่อสร้างออนไลน์ที่อยู่ใจกลางชุมชนวงการธุรกิจก่อสร้างที่มีลูกค้าค้นหาบริการของท่านตลอดเวลา
• ระบบช่วยให้ลูกค้าของคุณสามารถค้นหาสินค้าและบริการของท่าน และติดต่อหาท่านโดยตรงทั้งทาง โทรศัพท์ , Line@ , messenger หรือดูข้อมูลของท่านเพิ่มเติมจากทาง Website หรือ Facebook fanpage ของท่าน"
?>



<div class="site-login">
    <div class="container">

        <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
        <h1><?= Html::encode($this->title) ?></h1>

        <!-- <p>Please fill out the following fields to login:</p> -->




        <!-- <div class="site-login" style="display: flex; justify-content: center; align-items: center;">

            <div class="row">


                <div class="rounded mx-auto d-block ">
                    <img src="../common/web/img/logo-maxhome.png" style="height:150px;" alt="">
                </div>



                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <p>
                        สมัครสมาชิก / เข้าสู่ระบบ ง่ายๆ<br>ด้วยระบบ facebook <br> สะดวก ปลอดภัย
                    </p>


                    <?= Html::a(
                        '  สมัครสมาชิก / เข้าสู่ระบบ',
                        ['site/auth', 'authclient' => 'facebook'],
                        ['class' => 'btn btn-primary btn-block btn-lg fab fa-facebook-square', 'style' => 'background-color: #3b5998;']
                    )
                    ?>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <hr>
                </div>

                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <p>
                        สิทธิพิเศษสำหรับสมาชิก เท่านั้น<br>
                        1. ลงประกาศ "งานรับเหมาก่อสร้าง"<br>
                        2. ลงประกาศ "ร้านวัสดุก่อสร้าง"<br>
                        3. ลงประกาศ "สถาปนิก ออกแบบ / วิศวกร เขียนแบบ"
                    <p>

                    </p>
                </div>
            </div>
        </div> -->







        <div class="card2">
            <div class="card-body">
                <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                    <div class="rounded mx-auto d-block ">
                        <img src="../common/web/img/logo-maxhome.png" style="height:150px;" alt="">
                    </div>
                    <p>
                        สมัครสมาชิก / เข้าสู่ระบบ ง่ายๆ<br>ด้วยระบบ facebook และ google<br> สะดวก ปลอดภัย
                    </p>
                </div>

                <div class="row">

                    <div class="col-xs-6 col-sm-6 col-md-6">



                        <?= $form->field($model, 'user_name') ?>
                        <?= $form->field($model, 'user_password')->passwordInput() ?>
                        <?= '' //$form->field($model, 'rememberMe')->checkbox(['id' => 'remember-me-ver', 'custom' => true]) 
                        ?>

                        <div class="form-group ">
                            <?= Html::submitButton('เข้าสู่ระบบ', ['class' => 'btn btn-primary']) ?>
                            <?= Html::a('สมัครสมาชิก', ['mh-user/register'], ['class' => 'btn btn-secondary']) ?>
                        </div>

                        <hr class="hr-text" data-content="OR">
                        <!--<div class="separator">or login social</div>-->

                        <div class="text-center" style="padding-top: 20px;">
                            <?= Html::a(
                                '  สมัครสมาชิก / เข้าสู่ระบบ',
                                ['site/auth', 'authclient' => 'facebook'],
                                ['class' => 'btn btn-primary  btn-lg fab fa-facebook-square ', 'style' => 'background-color: #3b5998; ']
                            )
                            ?>
                            <br>
                            <br>
                            <?= Html::a(
                                '  สมัครสมาชิก / เข้าสู่ระบบ',
                                ['site/auth', 'authclient' => 'google'],
                                ['class' => ' btn btn-danger btn-lg fab fa-google-plus-square ', 'style' => 'background-color: #ef5350; color:#FFFFFF ']
                            )
                            ?>
                        </div>


                    </div>






                    <div class="col-xs-6 col-sm-6 col-md-6">


                        <div class="col-xs-12 col-sm-12 col-md-12">

                            <h6 class="text-center" style="color : red; padding-top:30px;"><strong><u>***สิทธิพิเศษสำหรับสมาชิก เท่านั้น***</u></strong><br></h6><br>
                            <p>
                                สิทธิพิเศษสำหรับสมาชิก เท่านั้น<br>
                                1. ลงประกาศ "งานรับเหมาก่อสร้าง"<br>
                                2. ลงประกาศ "ร้านวัสดุก่อสร้าง"<br>
                                3. ลงประกาศ "สถาปนิก ออกแบบ / วิศวกร เขียนแบบ"
                            <p>
                        </div>

                    </div>

                </div>
            </div>
        </div>




        <?php ActiveForm::end(); ?>






    </div>
</div>

frontend/views/mh-user/profile.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

$this->title = $model->user_firstname;
$userid = yii::$app->user->identity->id;
//$this->params['breadcrumbs'][] = ['label' => 'ข้อมูลผู้ใช้', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>

<body style="background-color: #ecf0f3;">

<div class="row">

        

    <div class="container">

        <div class="card2">
            <div class="card-body">
                <h4>เลือกประเภทกิจการของฉัน</h4>
            <br>
                <div class="row">
                    <div class="col-sm-3 col-lg-2">
                        <div class="form-group">
                            <?= Html::a('ผู้รับเหมาก่อสร้าง', ['mh-job/myjob' , 'id' => $model->user_id],
                            ['class' => 'btn button-commany pink btn-sm btn-block']) ?>
                        </div>
                    </div>

                    <div class="col-sm-3 col-lg-2">
                        <div class="form-group">
                            <?= Html::a('ร้านวัสดุก่อสร้าง', ['mh-construction/mycons' , 'id' => $model->user_id],
                            ['class' => 'btn button-commany danger btn-sm btn-block']) ?>
                        </div>
                    </div>

                    <div class="col-sm-4 col-md-5 col-lg-4">
                        <div class="form-group">
                            <?= Html::a('สถาปนิกออกแบบ / วิศวกรเขียนแบบ', ['mh-architect-engineer/myae'],
                            ['class' => 'btn btn-success btn-sm btn-block']) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>

<!--<div class="rog-user-car-index">
    <?= Html::a('ประวัติการสั่งคอนกรีต', ['mh-concrete/mycon']) ?>
    <br>
    
</div>-->


<div class="">
            <p> </p>
        </div>



        <div class="card2">
            <div class="card-body">
            <h2><?= Html::encode($this->title) ?></h2>

                    <?php 
                    if (yii::$app->user->identity->id == $model->user_id) {
                        echo '<p>';
                        echo Html::a('แก้ไขรายละเอียด', ['mh-user/update', 'id' => $model->user_id], ['class' => 'btn btn-primary']);
                        echo '</p>';
                    }
                    ?>

                    <?=DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            //'user_id',
                            //'user_name',
                            'user_firstname',
                            'user_lastname',
                            'user_tel1',
                            'user_tel2',
                            'user_line_id',
                            //'user_line_ad',
                            'user_fb_url:url',
                            'user_messenger',
                            'user_email:email',
                            'user_website',
                            'user_other',
                            //'updated_id',
                            'created_time:datetime',
                            'updated_time:datetime',
                        ],
                    ]) ?>
            </div>
        </div>


        <div class="">
            <p> </p>
        </div>


<div class="card2">
    <div class="card-body">
        <div class="">
            <p>เมื่อท่านสมาชิกกรอกข้อมูลติดต่อเรียบร้อย ท่านสามารถใช้บริการลงประกาศใน Hub.MAXHOME.co ได้เลยค่ะ</p>
        </div>


        <div class="">
            <?= Html::a(
                'กลับสู้หน้าหลัก Hub.MAXHOME.co',
                ['site/index'],
                ['class' => 'btn btn-danger btn-block btn-sm', 'style' => '']
            ) ?>
        </div>
    </div>
</div>    

<div class="">
            <p> </p>
        </div>


        
    </div>
</div>

</body>